import { Component, OnInit } from '@angular/core';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-root',
  template: `
    <router-outlet></router-outlet>
  `
})
export class AppComponent implements OnInit {
  /**
   * Root component that serves as the entry point for the application.
   * 
   * In the Angular architecture, this replaces the AngularJS bootstrap process.
   * Instead of manually bootstrapping the app with angular.bootstrap(),
   * Angular's main.ts handles bootstrapping using platformBrowserDynamic().
   * 
   * The AppModule (not shown here) now imports and configures all the required
   * feature modules that were previously loaded as AngularJS modules.
   */
  
  /**
   * Application constants moved to environment configuration
   * These would be accessed via environment.apiUrl, etc. throughout the app
   */
  appConstants = environment;

  constructor() {
    // No need for explicit DI here as it's handled by Angular's DI system
    // The strictDi: true option from AngularJS is replaced by TypeScript's
    // strong typing and Angular's DI system
  }

  ngOnInit(): void {
    // Any initialization logic that was in appRun can be placed here
    // For example, checking authentication status on app start
    
    // Note: In a real application, auth initialization would typically
    // be handled by an AuthService and AuthGuard in the routing module
  }
}

/**
 * Migration Notes:
 * 
 * 1. Module Structure:
 *    - AngularJS modules ('app.layout', 'app.components', etc.) are now
 *      feature modules in Angular, imported in the AppModule
 *    - Each feature module has its own routing configuration
 * 
 * 2. Routing:
 *    - 'ui.router' is replaced by Angular Router (@angular/router)
 *    - Routing configuration is now in app-routing.module.ts and feature module routing files
 * 
 * 3. Templates:
 *    - Templates generated by Gulp are now component-specific HTML files or inline templates
 * 
 * 4. Services:
 *    - AngularJS services are now Injectable classes in Angular
 * 
 * 5. Constants:
 *    - AppConstants are now in environment.ts and environment.prod.ts
 * 
 * 6. Configuration:
 *    - appConfig is now handled by Angular module providers and app initialization
 * 
 * 7. Bootstrap Process:
 *    - Manual bootstrap is replaced by Angular's bootstrap process in main.ts
 *    - strictDi is enforced by TypeScript and Angular's DI system
 */